# Generated by Django 4.2.16 on 2025-07-29 14:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning", "0002_alter_pathachievement_rarity"),
        ("icfes", "0003_areaevaluacion_areatematica_competenciaicfes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("explanation", "Explanation"),
                            ("hint", "Hint"),
                            ("tutoring", "Tutoring"),
                            ("analysis", "Analysis"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Datos de contexto de la conversación"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, help_text="Número total de mensajes"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0, help_text="Total de tokens utilizados"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.00"),
                        help_text="Costo total de la conversación",
                        max_digits=10,
                    ),
                ),
                (
                    "user_satisfaction",
                    models.IntegerField(
                        blank=True,
                        help_text="Satisfacción del usuario (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_conversations",
            },
        ),
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("explanation_request", "Explanation Request"),
                            ("hint_request", "Hint Request"),
                            ("analysis_request", "Analysis Request"),
                            ("conversation_start", "Conversation Start"),
                            ("conversation_end", "Conversation End"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, help_text="Datos de entrada"),
                ),
                (
                    "output_data",
                    models.JSONField(default=dict, help_text="Datos de salida"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0, help_text="Total de tokens utilizados"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.00"),
                        help_text="Costo de la interacción",
                        max_digits=10,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0, help_text="Tiempo de procesamiento en ms"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si aplica"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, help_text="ID de sesión", max_length=100
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Dirección IP", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent del cliente"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_interaction_logs",
            },
        ),
        migrations.CreateModel(
            name="AILearningInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("strength_analysis", "Strength Analysis"),
                            ("weakness_identification", "Weakness Identification"),
                            ("learning_pattern", "Learning Pattern"),
                            ("recommendation", "Recommendation"),
                            ("progress_tracking", "Progress Tracking"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "learning_patterns",
                    models.JSONField(
                        default=dict, help_text="Patrones de aprendizaje identificados"
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(default=dict, help_text="Fortalezas del usuario"),
                ),
                (
                    "weaknesses",
                    models.JSONField(default=dict, help_text="Debilidades del usuario"),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=dict, help_text="Recomendaciones personalizadas"
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si el insight está activo"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de validez del insight", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_learning_insights",
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Contenido del mensaje")),
                (
                    "tokens_input",
                    models.IntegerField(default=0, help_text="Tokens de entrada"),
                ),
                (
                    "tokens_output",
                    models.IntegerField(default=0, help_text="Tokens de salida"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Tiempo de respuesta en milisegundos"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Puntuación de confianza (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Metadatos adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del modelo", max_length=200
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("meta", "Meta"),
                            ("custom", "Custom"),
                        ],
                        help_text="Proveedor del modelo",
                        max_length=20,
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        help_text="Identificador único del modelo (ej: gpt-4, claude-3)",
                        max_length=100,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("explanation", "Explanation"),
                            ("hint", "Hint"),
                            ("conversation", "Conversation"),
                            ("analysis", "Analysis"),
                            ("generation", "Generation"),
                        ],
                        help_text="Propósito principal del modelo",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Configuración específica del modelo"
                    ),
                ),
                (
                    "cost_per_1k_tokens",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Costo por 1000 tokens (input + output)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4096, help_text="Máximo número de tokens permitidos"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si el modelo está disponible para uso"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si es el modelo por defecto para su propósito",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre del template", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único del template",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("explanation", "Explanation"),
                            ("hint", "Hint"),
                            ("analysis", "Analysis"),
                            ("feedback", "Feedback"),
                            ("motivation", "Motivation"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del template"),
                ),
                ("system_prompt", models.TextField(help_text="Prompt del sistema")),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template del prompt del usuario con {{variables}}"
                    ),
                ),
                (
                    "required_variables",
                    models.JSONField(
                        default=list, help_text="Lista de variables requeridas"
                    ),
                ),
                (
                    "model_config",
                    models.JSONField(
                        default=dict, help_text="Configuración específica del modelo"
                    ),
                ),
                (
                    "role_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TANK", "Tank"),
                            ("DPS", "DPS"),
                            ("SUPPORT", "Support"),
                            ("ALL", "All"),
                        ],
                        help_text="Filtro por rol de usuario",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effectiveness_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Puntuación de efectividad (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="Número de veces usado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si el template está activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_templates",
                        to="icfes.areatematica",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prompt_templates",
            },
        ),
        migrations.CreateModel(
            name="AIUsageQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=50, help_text="Límite diario de interacciones"
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        default=1000, help_text="Límite mensual de interacciones"
                    ),
                ),
                (
                    "used_today",
                    models.IntegerField(
                        default=0, help_text="Interacciones usadas hoy"
                    ),
                ),
                (
                    "used_this_month",
                    models.IntegerField(
                        default=0, help_text="Interacciones usadas este mes"
                    ),
                ),
                (
                    "last_reset_daily",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Último reset diario"
                    ),
                ),
                (
                    "last_reset_monthly",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Último reset mensual"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Si el usuario tiene plan premium"
                    ),
                ),
                (
                    "custom_limits",
                    models.JSONField(default=dict, help_text="Límites personalizados"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_quotas",
            },
        ),
        migrations.CreateModel(
            name="AIResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        help_text="Clave única del caché (SHA256)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "response_content",
                    models.TextField(help_text="Contenido de la respuesta cacheada"),
                ),
                ("tokens_used", models.IntegerField(help_text="Tokens utilizados")),
                (
                    "user_satisfaction_avg",
                    models.FloatField(
                        default=0.0,
                        help_text="Satisfacción promedio de usuarios",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "serve_count",
                    models.IntegerField(default=0, help_text="Número de veces servido"),
                ),
                ("last_served", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Fecha de expiración del caché"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_responses",
                        to="ai_llm.aimodel",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_responses",
                        to="icfes.preguntaicfes",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_responses",
                        to="ai_llm.aiprompttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "ai_response_cache",
            },
        ),
        migrations.CreateModel(
            name="AIPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Fecha de la métrica")),
                (
                    "total_requests",
                    models.IntegerField(default=0, help_text="Total de requests"),
                ),
                (
                    "avg_response_time_ms",
                    models.FloatField(
                        default=0.0, help_text="Tiempo promedio de respuesta en ms"
                    ),
                ),
                (
                    "error_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Tasa de error (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_satisfaction_avg",
                    models.FloatField(
                        default=0.0,
                        help_text="Satisfacción promedio de usuarios (0-5)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.00"),
                        help_text="Costo total del día",
                        max_digits=10,
                    ),
                ),
                (
                    "cache_hit_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Tasa de acierto del caché (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "p95_response_time",
                    models.FloatField(
                        default=0.0, help_text="Percentil 95 del tiempo de respuesta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="ai_llm.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "ai_performance_metrics",
            },
        ),
        migrations.CreateModel(
            name="AIModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flagged_content",
                    models.TextField(help_text="Contenido marcado como problemático"),
                ),
                (
                    "flag_reason",
                    models.CharField(
                        choices=[
                            ("inappropriate_content", "Inappropriate Content"),
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("misinformation", "Misinformation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ai_action_taken",
                    models.CharField(
                        choices=[
                            ("blocked", "Blocked"),
                            ("flagged", "Flagged"),
                            ("warned", "Warned"),
                            ("allowed", "Allowed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "human_reviewed",
                    models.BooleanField(
                        default=False, help_text="Si fue revisado por un humano"
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_logs",
                        to="ai_llm.aiconversation",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_moderation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_moderation_logs",
            },
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["provider", "purpose"], name="ai_models_provide_143b16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["is_active", "is_default"], name="ai_models_is_acti_d67d26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "model_identifier", "purpose")},
        ),
        migrations.AddField(
            model_name="aimessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_llm.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="model_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="ai_llm.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="ailearninginsight",
            name="generated_by_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_insights",
                to="ai_llm.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="ailearninginsight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiinteractionlog",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interaction_logs",
                to="ai_llm.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="aiinteractionlog",
            name="model_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interaction_logs",
                to="ai_llm.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="aiinteractionlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="area_evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_conversations",
                to="icfes.areaevaluacion",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="learning_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_conversations",
                to="learning.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="pregunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_conversations",
                to="icfes.preguntaicfes",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsecache",
            index=models.Index(
                fields=["cache_key"], name="ai_response_cache_k_247cf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsecache",
            index=models.Index(
                fields=["expires_at"], name="ai_response_expires_cabb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsecache",
            index=models.Index(
                fields=["prompt_template", "pregunta"],
                name="ai_response_prompt__bc27e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(
                fields=["category", "is_active"], name="ai_prompt_t_categor_58bb4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(
                fields=["role_filter", "is_active"],
                name="ai_prompt_t_role_fi_569f4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(
                fields=["effectiveness_score"], name="ai_prompt_t_effecti_6077a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiperformancemetric",
            index=models.Index(
                fields=["date", "model"], name="ai_performa_date_134584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiperformancemetric",
            index=models.Index(
                fields=["model", "date"], name="ai_performa_model_i_6e0e35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiperformancemetric",
            unique_together={("date", "model")},
        ),
        migrations.AddIndex(
            model_name="aimoderationlog",
            index=models.Index(
                fields=["user", "created_at"], name="ai_moderati_user_id_4b482a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimoderationlog",
            index=models.Index(
                fields=["flag_reason", "severity"],
                name="ai_moderati_flag_re_26f209_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimoderationlog",
            index=models.Index(
                fields=["human_reviewed", "final_decision"],
                name="ai_moderati_human_r_d37135_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_messages_convers_15163f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["role", "created_at"], name="ai_messages_role_edbf18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ailearninginsight",
            index=models.Index(
                fields=["user", "insight_type"], name="ai_learning_user_id_3f030c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ailearninginsight",
            index=models.Index(
                fields=["confidence_level", "is_active"],
                name="ai_learning_confide_92b6df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailearninginsight",
            index=models.Index(
                fields=["valid_until"], name="ai_learning_valid_u_3c2caf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["user", "created_at"], name="ai_interact_user_id_610177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["interaction_type", "created_at"],
                name="ai_interact_interac_e83e74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["model_used", "created_at"],
                name="ai_interact_model_u_45fe61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user_id", "status"], name="ai_conversa_user_id_59068a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["conversation_type", "status"],
                name="ai_conversa_convers_32faee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["started_at"], name="ai_conversa_started_f9847d_idx"
            ),
        ),
    ]
