# Generated by Django 4.2.23 on 2025-07-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icfes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniversitygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usericfessession',
            name='icfes_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icfes.icfesexam'),
        ),
        migrations.AddField(
            model_name='usericfessession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icfes_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='universityadmission',
            index=models.Index(fields=['min_global_score', 'is_active'], name='university__min_glo_c21f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='universityadmission',
            index=models.Index(fields=['university_name', 'program_name'], name='university__univers_a8c4e8_idx'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icfesresult',
            name='icfes_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icfes.icfesexam'),
        ),
        migrations.AddField(
            model_name='icfesresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='icfes.usericfessession'),
        ),
        migrations.AddField(
            model_name='icfesresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icfes_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icfesprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icfes_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='icfesexam',
            index=models.Index(fields=['exam_type', 'is_active'], name='icfes_exams_exam_ty_7ca47f_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesexam',
            index=models.Index(fields=['period', 'is_official'], name='icfes_exams_period_a8450c_idx'),
        ),
        migrations.AddIndex(
            model_name='useruniversitygoal',
            index=models.Index(fields=['user', 'status'], name='user_univer_user_id_9ff7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='useruniversitygoal',
            index=models.Index(fields=['status', 'priority'], name='user_univer_status_9f5114_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useruniversitygoal',
            unique_together={('user', 'university_admission')},
        ),
        migrations.AddIndex(
            model_name='usericfessession',
            index=models.Index(fields=['user', 'status'], name='user_icfes__user_id_d59219_idx'),
        ),
        migrations.AddIndex(
            model_name='usericfessession',
            index=models.Index(fields=['status', 'created_at'], name='user_icfes__status_de59c4_idx'),
        ),
        migrations.AddIndex(
            model_name='usericfessession',
            index=models.Index(fields=['icfes_exam', 'session_type'], name='user_icfes__icfes_e_2298ad_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'status'], name='study_plans_user_id_2d6fba_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['status', 'target_exam_date'], name='study_plans_status_32896d_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesresult',
            index=models.Index(fields=['user', 'created_at'], name='icfes_resul_user_id_c5a37f_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesresult',
            index=models.Index(fields=['global_score', 'is_official'], name='icfes_resul_global__467368_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesresult',
            index=models.Index(fields=['icfes_exam', 'global_score'], name='icfes_resul_icfes_e_234f42_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesprediction',
            index=models.Index(fields=['user', 'prediction_date'], name='icfes_predi_user_id_d761a7_idx'),
        ),
        migrations.AddIndex(
            model_name='icfesprediction',
            index=models.Index(fields=['prediction_type', 'confidence_level'], name='icfes_predi_predict_608eed_idx'),
        ),
    ]
