# Generated by Django 4.2.23 on 2025-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icfes', '0003_areaevaluacion_areatematica_competenciaicfes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuarioicfes',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='Puntuación de confianza de la IA'),
        ),
        migrations.AddField(
            model_name='respuestausuarioicfes',
            name='ai_explanation_provided',
            field=models.TextField(blank=True, help_text='Explicación generada por IA', null=True),
        ),
        migrations.AddField(
            model_name='respuestausuarioicfes',
            name='ai_explanation_requested',
            field=models.BooleanField(default=False, help_text='Si se solicitó explicación con IA'),
        ),
        migrations.AddField(
            model_name='respuestausuarioicfes',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text='Modelo de IA utilizado', max_length=100, null=True),
        ),
    ]
