# Generated by Django 4.2.23 on 2025-07-31 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icfes', '0004_respuestausuarioicfes_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('ABANDONED', 'Abandonada')], default='ACTIVE', max_length=20)),
                ('incorrect_questions', models.JSONField(default=list, help_text='Lista de IDs de preguntas incorrectas')),
                ('current_question_index', models.IntegerField(default=0, help_text='Índice de la pregunta actual en el feedback')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='icfes.usericfessession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Feedback',
                'verbose_name_plural': 'Sesiones de Feedback',
                'db_table': 'feedback_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressiveFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(choices=[(1, 'Nivel 1 - Básico'), (2, 'Nivel 2 - Intermedio'), (3, 'Nivel 3 - Detallado')], default=1)),
                ('max_level_reached', models.IntegerField(default=1)),
                ('student_understood', models.BooleanField(default=False)),
                ('explanation_level_1', models.TextField(blank=True, help_text='Explicación básica', null=True)),
                ('explanation_level_2', models.TextField(blank=True, help_text='Explicación intermedia', null=True)),
                ('explanation_level_3', models.TextField(blank=True, help_text='Explicación detallada', null=True)),
                ('llm_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('generation_time_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_feedbacks', to='icfes.feedbacksession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_feedbacks', to='icfes.preguntaicfes')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_feedbacks', to='icfes.respuestausuarioicfes')),
            ],
            options={
                'verbose_name': 'Feedback Progresivo',
                'verbose_name_plural': 'Feedbacks Progresivos',
                'db_table': 'progressive_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('feedback_session', 'question')},
            },
        ),
    ]
