# Generated by Django 4.2.16 on 2025-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathachievement",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("COMMON", "Común"),
                    ("RARE", "Raro"),
                    ("EPIC", "Épico"),
                    ("LEGENDARY", "Legendario"),
                ],
                default="COMMON",
                max_length=20,
            ),
        ),
    ]
