# Generated by Django 4.2.23 on 2025-07-15 17:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementGlobal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('INFO', 'Información'), ('UPDATE', 'Actualización'), ('MAINTENANCE', 'Mantenimiento'), ('EVENT', 'Evento'), ('PROMOTION', 'Promoción'), ('EMERGENCY', 'Emergencia')], max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'Crítica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja'), (5, 'Informativa')], default=3)),
                ('banner_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_theme', models.CharField(default='#3B82F6', max_length=7)),
                ('action_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('target_audience', models.JSONField(default=dict)),
                ('min_user_level', models.IntegerField(default=1)),
                ('specific_user_groups', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_banner', models.BooleanField(default=False)),
                ('show_as_popup', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'announcements_global',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagen'), ('FILE', 'Archivo'), ('SYSTEM', 'Sistema'), ('ACHIEVEMENT', 'Logro'), ('BATTLE_RESULT', 'Resultado de Batalla')], default='TEXT', max_length=15)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('thread_type', models.CharField(choices=[('DIRECT', 'Mensaje Directo'), ('ACADEMY', 'Academia'), ('BATTLE', 'Batalla'), ('GROUP', 'Grupo'), ('SUPPORT', 'Soporte')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('messages_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_threads',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('ACHIEVEMENT', 'Logro'), ('SOCIAL', 'Social'), ('REMINDER', 'Recordatorio'), ('SYSTEM', 'Sistema')], max_length=15)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_theme', models.CharField(default='#3B82F6', max_length=7)),
                ('action_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('action_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviada'), ('DELIVERED', 'Entregada'), ('READ', 'Leída'), ('CLICKED', 'Clickeada'), ('FAILED', 'Fallida'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=15)),
                ('priority', models.IntegerField(default=3)),
                ('channel', models.CharField(default='IN_APP', max_length=10)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('ACHIEVEMENT', 'Logro Desbloqueado'), ('LEVEL_UP', 'Subida de Nivel'), ('BATTLE_INVITE', 'Invitación a Batalla'), ('BATTLE_RESULT', 'Resultado de Batalla'), ('ACADEMY_INVITE', 'Invitación a Academia'), ('ACADEMY_NEWS', 'Noticias de Academia'), ('STUDY_REMINDER', 'Recordatorio de Estudio'), ('EXAM_REMINDER', 'Recordatorio de Examen'), ('WEEKLY_REPORT', 'Reporte Semanal'), ('FRIEND_ACTIVITY', 'Actividad de Amigos'), ('SYSTEM_UPDATE', 'Actualización del Sistema'), ('PROMOTION', 'Promoción'), ('WELCOME', 'Bienvenida'), ('GOAL_PROGRESS', 'Progreso de Objetivos')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('action_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_theme', models.CharField(default='#3B82F6', max_length=7)),
                ('priority_level', models.IntegerField(default=3)),
                ('supported_channels', models.JSONField(default=list)),
                ('default_channel', models.CharField(choices=[('IN_APP', 'En la App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=10)),
                ('immediate_send', models.BooleanField(default=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('respect_quiet_hours', models.BooleanField(default=True)),
                ('allowed_variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Miembro'), ('ADMIN', 'Administrador'), ('MODERATOR', 'Moderador')], default='MEMBER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thread_participants',
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('view_source', models.CharField(default='banner', max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_announcement_views',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achievements_enabled', models.BooleanField(default=True)),
                ('battle_invites_enabled', models.BooleanField(default=True)),
                ('academy_updates_enabled', models.BooleanField(default=True)),
                ('study_reminders_enabled', models.BooleanField(default=True)),
                ('weekly_reports_enabled', models.BooleanField(default=True)),
                ('friend_activity_enabled', models.BooleanField(default=True)),
                ('system_updates_enabled', models.BooleanField(default=True)),
                ('promotions_enabled', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=True)),
                ('quiet_start_time', models.TimeField(default='22:00:00')),
                ('quiet_end_time', models.TimeField(default='08:00:00')),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Inmediato'), ('HOURLY', 'Cada Hora'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='IMMEDIATE', max_length=10)),
                ('preferred_language', models.CharField(default='es', max_length=5)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_notification_settings',
            },
        ),
    ]
