# Generated by Django 4.2.23 on 2025-07-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpowerup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userleaguestatus',
            name='current_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.league'),
        ),
        migrations.AddField(
            model_name='userleaguestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'is_active'], name='achievement_categor_79c57c_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['rarity', 'is_secret'], name='achievement_rarity_16cbf7_idx'),
        ),
        migrations.AddField(
            model_name='academymembership',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gamification.academy'),
        ),
        migrations.AddField(
            model_name='academymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='co_leaders',
            field=models.ManyToManyField(blank=True, related_name='co_led_academies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academies', to='gamification.district'),
        ),
        migrations.AddField(
            model_name='academy',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_academies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpowerup',
            index=models.Index(fields=['user', 'is_active'], name='user_poweru_user_id_63ff58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpowerup',
            unique_together={('user', 'powerup')},
        ),
        migrations.AddIndex(
            model_name='usercurrency',
            index=models.Index(fields=['user', 'currency_type'], name='user_curren_user_id_8963c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together={('user', 'currency_type')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_completed'], name='user_achiev_user_id_171932_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement', 'completed_at'], name='user_achiev_achieve_f073d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', 'created_at'], name='battles_status_efa56d_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['challenger', 'status'], name='battles_challen_07a855_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['opponent', 'status'], name='battles_opponen_bfb300_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['battle_type', 'completed_at'], name='battles_battle__b3a0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='academymembership',
            index=models.Index(fields=['academy', 'is_active'], name='academy_mem_academy_db094d_idx'),
        ),
        migrations.AddIndex(
            model_name='academymembership',
            index=models.Index(fields=['user', 'is_active'], name='academy_mem_user_id_47f6a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academymembership',
            unique_together={('user', 'academy')},
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['district', 'specialty'], name='academies_distric_70b328_idx'),
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['is_active', 'is_recruiting'], name='academies_is_acti_430d5a_idx'),
        ),
    ]
