# Generated by Django 4.2.23 on 2025-07-15 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_text', models.TextField()),
                ('question_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('question_audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil'), ('EXPERT', 'Experto')], max_length=10)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Opción Múltiple'), ('TRUE_FALSE', 'Verdadero/Falso'), ('OPEN_ENDED', 'Respuesta Abierta')], default='MULTIPLE_CHOICE', max_length=20)),
                ('source_type', models.CharField(choices=[('ICFES_OFFICIAL', 'ICFES Oficial'), ('CUADERNILLO', 'Cuadernillo ICFES'), ('PRACTICE', 'Práctica'), ('AI_GENERATED', 'Generada por IA')], default='PRACTICE', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('times_asked', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('average_time_seconds', models.FloatField(default=0.0)),
                ('ai_explanation_prompt', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionExplanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation_type', models.CharField(choices=[('SOLUTION', 'Solución'), ('HINT', 'Pista'), ('THEORY', 'Teoría'), ('AI_GENERATED', 'Generada por IA')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil'), ('EXPERT', 'Experto')], default='MEDIUM', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_explanations',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_letter', models.CharField(max_length=1)),
                ('option_text', models.TextField()),
                ('option_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order', 'option_letter'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('set_type', models.CharField(choices=[('PRACTICE', 'Práctica'), ('EXAM', 'Examen'), ('BATTLE', 'Batalla'), ('ASSESSMENT', 'Evaluación'), ('CUADERNILLO', 'Cuadernillo')], max_length=20)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_filter', models.CharField(blank=True, choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil'), ('EXPERT', 'Experto')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'question_set_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('MATHEMATICS', 'Matemáticas'), ('READING', 'Lectura Crítica'), ('NATURAL_SCIENCES', 'Ciencias Naturales'), ('SOCIAL_STUDIES', 'Ciencias Sociales'), ('ENGLISH', 'Inglés')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_theme', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('response_time_seconds', models.FloatField()),
                ('confidence_level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quiz_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_explanation_requested', models.BooleanField(default=False)),
                ('ai_explanation_provided', models.TextField(blank=True, null=True)),
                ('difficulty_perceived', models.CharField(blank=True, choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil'), ('EXPERT', 'Experto')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionoption')),
            ],
            options={
                'db_table': 'user_question_responses',
            },
        ),
    ]
