# Generated by Django 4.2.23 on 2025-07-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='prerequisite_topics',
            field=models.ManyToManyField(blank=True, to='questions.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='questions.subject'),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionset'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(through='questions.QuestionSetItem', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='subject_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.subject'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='topic_filters',
            field=models.ManyToManyField(blank=True, to='questions.topic'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionexplanation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionexplanation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='questions.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic'),
        ),
        migrations.AddIndex(
            model_name='userquestionresponse',
            index=models.Index(fields=['user', 'created_at'], name='user_questi_user_id_86c078_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionresponse',
            index=models.Index(fields=['question', 'is_correct'], name='user_questi_questio_e877b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionresponse',
            index=models.Index(fields=['session_id'], name='user_questi_session_2e6655_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'is_active'], name='topics_subject_1a78c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsetitem',
            unique_together={('question_set', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('question', 'option_letter')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty'], name='questions_subject_3c5e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_active'], name='questions_topic_i_26873d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_type', 'is_verified'], name='questions_source__84bad9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='questions_created_2d11fa_idx'),
        ),
    ]
