# Generated by Django 4.2.23 on 2025-07-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_type',
            field=models.CharField(choices=[('TEXT_ONLY', 'Solo Texto'), ('WITH_IMAGE', 'Con Imagen'), ('WITH_GRAPH', 'Con Gráfica'), ('WITH_TABLE', 'Con Tabla'), ('WITH_DIAGRAM', 'Con Diagrama'), ('MULTIMEDIA', 'Multimedia')], default='TEXT_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='detected_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='diagram_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='extraction_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='extraction_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='geometric_figures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='graph_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='has_diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='has_graph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='has_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='manual_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mathematical_notation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='official_answer_key',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='statistical_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='table_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='word_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionexplanation',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'Todos'), ('TANK', 'Tanque'), ('DPS', 'Daño'), ('SUPPORT', 'Soporte'), ('SPECIALIST', 'Especialista')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='extraction_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='has_mathematical_notation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='adaptive_difficulty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='role_specific',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='dps_difficulty_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='specialist_difficulty_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='support_difficulty_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='questionsetitem',
            name='tank_difficulty_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='role_bonus_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='strategy_hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='xp_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Opción Múltiple'), ('TRUE_FALSE', 'Verdadero/Falso'), ('OPEN_ENDED', 'Respuesta Abierta'), ('MATCHING', 'Emparejamiento'), ('GRAPH_ANALYSIS', 'Análisis de Gráficas'), ('TABLE_ANALYSIS', 'Análisis de Tablas')], default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionexplanation',
            name='explanation_type',
            field=models.CharField(choices=[('SOLUTION', 'Solución'), ('HINT', 'Pista'), ('THEORY', 'Teoría'), ('AI_GENERATED', 'Generada por IA'), ('ROLE_BASED', 'Personalizada por Rol')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('PRACTICE', 'Práctica'), ('EXAM', 'Examen'), ('BATTLE', 'Batalla'), ('ASSESSMENT', 'Evaluación'), ('CUADERNILLO', 'Cuadernillo'), ('ICFES_SIMULATION', 'Simulacro ICFES')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionMultimedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('DIAGRAM', 'Diagrama'), ('GRAPH', 'Gráfica'), ('TABLE', 'Tabla'), ('CHART', 'Gráfico'), ('SCREENSHOT', 'Captura'), ('DRAWING', 'Dibujo')], max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='questions.question')),
            ],
            options={
                'db_table': 'question_multimedia',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICFESCuadernillo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cuadernillo_type', models.CharField(choices=[('SABER_11', 'Saber 11'), ('SABER_PRO', 'Saber Pro'), ('SIMULACRO', 'Simulacro'), ('PRACTICA', 'Práctica')], max_length=20)),
                ('period', models.CharField(choices=[('2024-1', '2024 Período 1'), ('2024-2', '2024 Período 2'), ('2023-1', '2023 Período 1'), ('2023-2', '2023 Período 2'), ('2022-1', '2022 Período 1'), ('2022-2', '2022 Período 2')], max_length=10)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('pdf_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('grade_level', models.IntegerField(default=11)),
                ('total_questions', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
            ],
            options={
                'db_table': 'icfes_cuadernillos',
                'ordering': ['-period', 'subject', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='cuadernillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.icfescuadernillo'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='cuadernillo_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.icfescuadernillo'),
        ),
        migrations.AddIndex(
            model_name='icfescuadernillo',
            index=models.Index(fields=['period', 'subject'], name='icfes_cuade_period_d961ca_idx'),
        ),
        migrations.AddIndex(
            model_name='icfescuadernillo',
            index=models.Index(fields=['cuadernillo_type', 'is_active'], name='icfes_cuade_cuadern_544119_idx'),
        ),
    ]
