# Generated by Django 4.2.23 on 2025-07-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['metric_type', 'calculated_at'], name='performance_metric__d77a72_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['metric_name', 'period_end'], name='performance_metric__0310c3_idx'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentanalytics',
            index=models.Index(fields=['content_type', 'success_rate'], name='content_ana_content_37b163_idx'),
        ),
        migrations.AddIndex(
            model_name='contentanalytics',
            index=models.Index(fields=['average_rating'], name='content_ana_average_177178_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentanalytics',
            unique_together={('content_type', 'content_id')},
        ),
        migrations.AddField(
            model_name='a_btest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usertestparticipation',
            index=models.Index(fields=['ab_test', 'variant'], name='user_test_p_ab_test_efe564_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestparticipation',
            index=models.Index(fields=['conversion_achieved'], name='user_test_p_convers_372c30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertestparticipation',
            unique_together={('user', 'ab_test')},
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'timestamp'], name='user_events_user_id_cf6bea_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='user_events_event_t_2c71bd_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['category', 'timestamp'], name='user_events_categor_0fc80a_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['session_id'], name='user_events_session_bff097_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectanalytics',
            index=models.Index(fields=['user', 'subject'], name='subject_ana_user_id_e49f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectanalytics',
            index=models.Index(fields=['accuracy_percentage'], name='subject_ana_accurac_583737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectanalytics',
            unique_together={('user', 'subject')},
        ),
        migrations.AddIndex(
            model_name='sessionanalytics',
            index=models.Index(fields=['user', 'started_at'], name='session_ana_user_id_60f05b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionanalytics',
            index=models.Index(fields=['session_type', 'started_at'], name='session_ana_session_b6d29e_idx'),
        ),
        migrations.AddIndex(
            model_name='a_btest',
            index=models.Index(fields=['status', 'start_date'], name='ab_tests_status_016a0e_idx'),
        ),
    ]
